# Generated by Django 5.2.4 on 2025-07-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0002_create_default_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
