# Generated by Django 5.2.6 on 2025-09-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctor", "0004_quizresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple Choice"),
                    ("tf", "True/False"),
                    ("blank", "Fill in the Blank"),
                    ("text", "Written Answer"),
                    ("match", "Matching"),
                    ("file", "File Upload"),
                ],
                default="mcq",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="section",
            field=models.CharField(blank=True, default="Default", max_length=100),
        ),
        migrations.AddField(
            model_name="studentresponse",
            name="matched_pairs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentresponse",
            name="text_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentresponse",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="quiz_uploads/"),
        ),
        migrations.AlterField(
            model_name="studentresponse",
            name="selected_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proctor.choice",
            ),
        ),
        migrations.CreateModel(
            name="BlankAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct_text", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blank_answers",
                        to="proctor.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left_text", models.CharField(max_length=255)),
                ("right_text", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_pairs",
                        to="proctor.question",
                    ),
                ),
            ],
        ),
    ]
