# Generated by Django 5.2.6 on 2025-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctor", "0006_alter_question_text_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="Match",
        ),
    ]
