# Generated by Django 5.2.4 on 2025-10-07 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0008_proctorevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('alert_type', models.CharField(choices=[('head_pose', 'Head Pose'), ('eye_gaze', 'Eye Gaze'), ('multi_face', 'Multiple Faces'), ('phone', 'Phone'), ('book', 'Book'), ('earphones', 'Earphones'), ('no_face', 'No Face'), ('audio_violation', 'Audio Violation'), ('looking_down', 'Looking Down'), ('looking_up', 'Looking Up'), ('rapid_movement', 'Rapid Movement'), ('face_verification', 'Face Verification (Mismatch)'), ('face_verification_match', 'Face Verification (Match)')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='proctor_snapshots/')),
                ('message', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
