# Generated by Django 5.2.4 on 2025-10-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0009_proctoralert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoralert',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proctor.quiz'),
        ),
    ]
