# Generated by Django 5.2.4 on 2025-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0010_alter_proctoralert_quiz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoralert',
            name='snapshot',
        ),
        migrations.AddField(
            model_name='proctoralert',
            name='snapshot_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoralert',
            name='snapshot_mime',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
    ]
