# Generated by Django 5.2.4 on 2025-10-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0011_remove_proctoralert_snapshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proctoralert',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
